# Generated by Django 6.1.1 on 2026-09-14 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='transactions_expenses',
        ),
    ]
