# Generated by Django 6.1.1 on 2026-09-14 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_savingstransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('salary', 'Income'), ('investment', 'Income'), ('business', 'Income'), ('other_income', 'Income'), ('food', 'Expense'), ('transportation', 'Expense'), ('housing', 'Expense'), ('utilities', 'Expense'), ('entertainment', 'Expense'), ('healthcare', 'Expense'), ('education', 'Expense'), ('personal_care', 'Expense'), ('debt_repayment', 'Expense'), ('savings', 'Expense'), ('other_expense', 'Expense')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
